# Generated by Django 5.1.6 on 2025-03-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/laptops.png', upload_to='songs/%Y/%m/%d/%h/%M/'),
        ),
    ]
